/**
 * ==============================================================================
 * PRODUCT DATA REPOSITORY
 * ==============================================================================
 * Centralized list of all products (Laptops and Software).
 * All prices are in Indian Rupees (₹).
 * Modifying this array updates the Featured list on index.html and catalog on shop.html.
 */

const PRODUCTS = [
  {
    id: "LAP-001",
    name: " DELL LATITUDE 5480",
    category: "laptop",
    brand: "Dell",
    price: 18000,
    originalPrice: 75000,
    condition: "Grade A+ (Like New)",
    processor: "Intel Core i5 6th Gen",
    ram: "8GB DDR4",
    storage: "256GB NVMe SSD",
    display: "14.0\"HD IPS (1920x1080) Anti-Glare",
    graphics: "Intel UHD Graphics 620",
    battery: "Tested Battery (3-4 hrs backup)",
    os: "Windows 11 Pro 64-bit Licensed",
    warranty: "1 Months Seller Testing Warranty",
    image: "assets/images/products/dell-latitude-5420.jpg",
    description: "Perfect for work, study, and everyday business use. With fast SSD performance and reliable Dell business-class build quality, this laptop is ready to handle office tasks, Tally, MS Office, browsing, online classes, and work-from-home needs.",
    featured: true,
    inStock: true,
    tags: ["Bestseller", "Slim & Light", "Enterprise"]
  },
  {
    id: "LAP-002",
    name: "DELL LATITUDE 5400 TOUCH",
    category: "laptop",
    brand: "Dell",
    price: 23000,
    originalPrice: 89000,
    condition: "Grade A (Excellent)",
    processor: "Intel Core i5 8th Gen",
    ram: "8GB DDR4 (Expandable to 64GB)",
    storage: "256GB PCIe M.2 NVMe SSD",
    display: "14.0\" FHD ComfortView WVA (1920x1080)",
    graphics: "Intel Iris Xe Graphics",
    battery: "Original Dell Battery (4+ hrs backup)",
    os: "Windows 11 Pro",
    warranty: " ",
    image: "assets/images/products/DELL LATITUDE 5400 TOUCH.jpeg",
    description: "Fresh Dell Latitude 5400 Touch with Core i5 8th Gen, 8GB RAM, and 256GB SSD. Featuring a backlit keyboard and A++ condition, it’s a reliable business laptop for work, study, and everyday productivity. Limited stock available.",
    featured: true,
    inStock: true,
    tags: ["8th Gen", "Fast SSD", "Iris Xe","Backlid Keyboard"]
  },
  {
    id: "LAP-003",
    name: "HP EliteBook 840 G6",
    category: "laptop",
    brand: "HP",
    price: 27000,
    originalPrice: 52000,
    condition: "Grade A+ (Pristine Aluminum)",
    processor: "Intel Core i7 8th Gen (8665U vPro)",
    ram: "8GB DDR4",
    storage: "256GB NVMe SSD",
    display: "13.3\" FHD IPS Anti-Glare Ultra Slim",
    graphics: "Intel UHD Graphics 620",
    battery: "Long Battery Backup",
    os: "Windows 11 Pro",
    warranty: " ",
    image: "assets/images/products/HP EliteBook 830 G6.jpeg",
    description: "Stunning full-metal aluminum unibody build with studio-tuned Bang & Olufsen speakers, backlit keyboard, fingerprint reader, and ultra-crisp display.",
    featured: true,
    inStock: true,
    tags: ["Core i7", "Full Aluminum", "Backlit Keyboard","Fingerprint Security"]
  },
  {
    id: "LAP-004",
    name: "DELL LATITUDE 5490",
    category: "laptop",
    brand: "Dell",
    price: 52999,
    originalPrice: 99900,
    condition: "Grade A+ (Flawless Space Grey)",
    processor: "Intel Core I7",
    ram: "8GB Ram",
    storage: "256GB SSD",
    display: "Full HD Display Resolution",
    graphics: "Intel UHD Graphics",
    battery: "Good Condition",
    os: "Window 11",
    warranty: " ",
    image: "assets/images/products/DELL LATITUDE 5490.jpeg",
    description: "Incredible speed, fanless silent operation, all-day battery life, and jaw-dropping Retina display. Ideal for content creators, designers, and mobile professionals.",
    featured: true,
    inStock: true,
    tags: ["Apple M1", "Retina", "All-Day Battery"]
  },
  {
    id: "LAP-005",
    name: "DELL PRECISION 3541",
    category: "laptop",
    brand: "Dell",
    price: 35000,
    originalPrice: 75000,
    condition: "Grade A (Ultra Premium)",
    processor: "INTEL CORE I7 9th Gen",
    ram: "8GB RAM ",
    storage: "512GB OPAL2 NVMe SSD",
    display: "15.6\" INCHES TOUCHSCREEN  ",
    graphics: "Intel UHD Graphics",
    battery: "Good Condition",
    os: "Windows 11 Pro",
    warranty: "6 Months Seller Testing Warranty",
    image: "assets/images/products/DELL PRECISION 3541.jpeg",
    description: "The gold standard of ultraportable business laptops. Built with carbon fiber reinforcement, weighing barely 1.09 kg with exceptional keyboard tactile feel and 400-nit screen.",
    featured: true,
    inStock: true,
    tags: ["Copper Body", "1.09 KG", "Core i7"]
  }
];
