/**
 * ==============================================================================
 * PRODUCT DATA REPOSITORY
 * ==============================================================================
 * Centralized list of all products (Laptops and Software).
 * All prices are in Indian Rupees (₹).
 * Modifying this array updates the Featured list on index.html and catalog on shop.html.
 */

const PRODUCTS = [
  {
    id: "LAP-001",
    name: "Lenovo ThinkPad T480s",
    category: "laptop",
    brand: "Lenovo",
    price: 23999,
    originalPrice: 75000,
    condition: "Grade A+ (Like New)",
    processor: "Intel Core i5 8th Gen (8350U)",
    ram: "16GB DDR4",
    storage: "512GB NVMe SSD",
    display: "14.0\" Full HD IPS (1920x1080) Anti-Glare",
    graphics: "Intel UHD Graphics 620",
    battery: "Tested Battery (3-4 hrs backup)",
    os: "Windows 11 Pro 64-bit Licensed",
    warranty: "6 Months Seller Testing Warranty",
    image: "assets/images/products/thinkpad-t480s.png",
    description: "Legendary ThinkPad durability with lightweight slim chassis, spill-resistant keyboard, rapid charging, and enterprise security features. Perfect for developers, corporate employees, and students.",
    featured: true,
    inStock: true,
    tags: ["Bestseller", "Slim & Light", "Enterprise"]
  },
  {
    id: "LAP-002",
    name: "Dell Latitude 5420",
    category: "laptop",
    brand: "Dell",
    price: 28499,
    originalPrice: 89000,
    condition: "Grade A (Excellent)",
    processor: "Intel Core i5 11th Gen (1145G7 with Iris Xe)",
    ram: "16GB DDR4 (Expandable to 64GB)",
    storage: "512GB PCIe M.2 NVMe SSD",
    display: "14.0\" FHD ComfortView WVA (1920x1080)",
    graphics: "Intel Iris Xe Graphics",
    battery: "Original Dell Battery (4+ hrs backup)",
    os: "Windows 11 Pro",
    warranty: "6 Months Seller Testing Warranty",
    image: "assets/images/products/dell-latitude-5420.jpg",
    description: "Modern 11th Gen powerhouse designed for multitasking, high-speed connectivity, and durable business performance. Features USB-C Thunderbolt 4 ports and HD webcam with privacy shutter.",
    featured: true,
    inStock: true,
    tags: ["11th Gen", "Fast SSD", "Iris Xe"]
  },
  {
    id: "LAP-003",
    name: "HP EliteBook 840 G6",
    category: "laptop",
    brand: "HP",
    price: 24999,
    originalPrice: 82000,
    condition: "Grade A+ (Pristine Aluminum)",
    processor: "Intel Core i7 8th Gen (8665U vPro)",
    ram: "16GB DDR4",
    storage: "512GB Turbo NVMe SSD",
    display: "14.0\" FHD IPS Anti-Glare Ultra Slim",
    graphics: "Intel UHD Graphics 620",
    battery: "Bang & Olufsen Audio + Tested 4h Battery",
    os: "Windows 11 Pro",
    warranty: "6 Months Seller Testing Warranty",
    image: "assets/images/products/hp-elitebook-840g6.jpg",
    description: "Stunning full-metal aluminum unibody build with studio-tuned Bang & Olufsen speakers, backlit keyboard, fingerprint reader, and ultra-crisp display.",
    featured: true,
    inStock: true,
    tags: ["Core i7", "Full Aluminum", "Backlit KB"]
  },
  {
    id: "LAP-004",
    name: "Apple MacBook Air 13\" (M1 Chip)",
    category: "laptop",
    brand: "Apple",
    price: 52999,
    originalPrice: 99900,
    condition: "Grade A+ (Flawless Space Grey)",
    processor: "Apple Silicon M1 8-Core CPU / 7-Core GPU",
    ram: "8GB Unified Memory",
    storage: "256GB High-Speed SSD",
    display: "13.3\" Retina Display with True Tone (2560x1600)",
    graphics: "Apple 7-Core GPU",
    battery: "Battery Health 92%+ (Up to 14 hrs life)",
    os: "macOS Sonoma Pre-installed",
    warranty: "3 Months Testing & Service Warranty",
    image: "assets/images/products/macbook-air-m1.jpg",
    description: "Incredible speed, fanless silent operation, all-day battery life, and jaw-dropping Retina display. Ideal for content creators, designers, and mobile professionals.",
    featured: true,
    inStock: true,
    tags: ["Apple M1", "Retina", "All-Day Battery"]
  },
  {
    id: "LAP-005",
    name: "Lenovo ThinkPad X1 Carbon Gen 7",
    category: "laptop",
    brand: "Lenovo",
    price: 33999,
    originalPrice: 135000,
    condition: "Grade A (Ultra Premium)",
    processor: "Intel Core i7 10th Gen (10510U)",
    ram: "16GB LPDDR3",
    storage: "512GB OPAL2 NVMe SSD",
    display: "14.0\" FHD Low-Power IPS 400 nits",
    graphics: "Intel UHD Graphics",
    battery: "Ultralight Carbon Fiber (1.09 kg)",
    os: "Windows 11 Pro",
    warranty: "6 Months Seller Testing Warranty",
    image: "assets/images/products/thinkpad-x1-carbon.png",
    description: "The gold standard of ultraportable business laptops. Built with carbon fiber reinforcement, weighing barely 1.09 kg with exceptional keyboard tactile feel and 400-nit screen.",
    featured: false,
    inStock: true,
    tags: ["Carbon Fiber", "1.09 KG", "Core i7"]
  },
  {
    id: "LAP-006",
    name: "Dell Precision 3541 Workstation",
    category: "laptop",
    brand: "Dell",
    price: 36999,
    originalPrice: 120000,
    condition: "Grade A (Heavy Duty Workstation)",
    processor: "Intel Core i7 9th Gen 6-Core (9750H)",
    ram: "32GB DDR4 High-Speed",
    storage: "1TB M.2 NVMe SSD",
    display: "15.6\" FHD IPS (1920x1080) 100% sRGB",
    graphics: "NVIDIA Quadro P620 4GB Dedicated",
    battery: "Heavy Duty 97Wh Battery",
    os: "Windows 11 Pro for Workstations",
    warranty: "6 Months Seller Testing Warranty",
    image: "assets/images/products/dell-precision-3541.jpg",
    description: "Heavy-duty mobile CAD/Design workstation with dedicated 4GB NVIDIA Quadro graphics, 32GB RAM, and 6-core processor. Built for AutoCAD, Premiere Pro, and 3D modeling.",
    featured: false,
    inStock: true,
    tags: ["CAD & Editing", "32GB RAM", "NVIDIA Quadro"]
  },
  {
    id: "LAP-007",
    name: "ASUS Vivobook 15 (Thin & Light)",
    category: "laptop",
    brand: "Asus",
    price: 26499,
    originalPrice: 58000,
    condition: "Grade A+ (Like New)",
    processor: "Intel Core i5 11th Gen (1135G7)",
    ram: "16GB DDR4 High-Speed",
    storage: "512GB PCIe M.2 SSD",
    display: "15.6\" FHD NanoEdge Anti-Glare (1920x1080)",
    graphics: "Intel Iris Xe Graphics",
    battery: "Fast Charging (4+ hrs backup)",
    os: "Windows 11 Home Licensed",
    warranty: "6 Months Seller Testing Warranty",
    image: "assets/images/products/asus-laptop.png",
    description: "Sleek and portable laptop featuring narrow NanoEdge bezel display, ergonomic keyboard, rapid SSD storage, and crisp audio. Excellent choice for work, study, and daily productivity.",
    featured: false,
    inStock: true,
    tags: ["NanoEdge", "Fast SSD", "Iris Xe"]
  },
  {
    id: "SFT-101",
    name: "Microsoft Office 2021 Professional Plus",
    category: "software",
    brand: "Microsoft",
    price: 1999,
    originalPrice: 14999,
    condition: "Lifetime Digital License",
    processor: "N/A",
    ram: "N/A",
    storage: "N/A",
    display: "N/A",
    graphics: "N/A",
    battery: "N/A",
    os: "Compatible with Windows 10 & 11",
    warranty: "Lifetime Activation Guarantee",
    image: "assets/images/products/software-ms-office.svg",
    description: "Full suite containing genuine lifetime keys for Word, Excel, PowerPoint, Outlook, OneNote, Publisher, and Access. 1 PC activation with official ISO download.",
    featured: true,
    inStock: true,
    tags: ["Lifetime License", "Office Suite", "Instant Delivery"]
  },
  {
    id: "SFT-102",
    name: "Windows 11 Pro Official OEM License",
    category: "software",
    brand: "Microsoft",
    price: 999,
    originalPrice: 9999,
    condition: "Lifetime Digital Activation",
    processor: "N/A",
    ram: "N/A",
    storage: "N/A",
    display: "N/A",
    graphics: "N/A",
    battery: "N/A",
    os: "Windows 11 Pro 64-bit",
    warranty: "Lifetime Activation Guarantee",
    image: "assets/images/products/software-windows-11.svg",
    description: "Genuine digital product key to upgrade or activate Windows 11 Pro. Unlocks BitLocker device encryption, Windows Sandbox, Remote Desktop, and Hyper-V.",
    featured: false,
    inStock: true,
    tags: ["Genuine OEM", "BitLocker", "Lifetime"]
  },
  {
    id: "SFT-103",
    name: "Quick Heal Total Security (1 PC / 3 Years)",
    category: "software",
    brand: "Quick Heal",
    price: 1499,
    originalPrice: 3200,
    condition: "3-Year Retail Box / Digital Key",
    processor: "N/A",
    ram: "N/A",
    storage: "N/A",
    display: "N/A",
    graphics: "N/A",
    battery: "N/A",
    os: "Windows 10, 11, macOS",
    warranty: "Full 3-Year Protection & Updates",
    image: "assets/images/products/software-antivirus.svg",
    description: "Comprehensive cybersecurity protection against ransomware, phishing, malware, banking fraud, and zero-day attacks with automatic cloud updates.",
    featured: false,
    inStock: true,
    tags: ["3-Year Protection", "Ransomware Shield", "Safe Banking"]
  }
];
